POST http://localhost:3000/meci_viitor
Content-Type: application/json

{
    "echipa_unu":"Simionescu",
    "echipa_doi":"Andrei-Gavril",
    "data":"2004-22-06"
}

###
DELETE http://localhost:3000/clasament/7
###
###
PUT http://localhost:3000/clasament/2
Content-Type: application/json

{
    "echipa": "Victoria2",
    "meciuri": 4,
    "victorii":6,
    "infrangeri":0,
    "seturi":"10",
    "puncte":100
}
###
DELETE http://localhost:3000/delete/28
###
GET http://localhost:3000/meci_viitor
###
POST http://localhost:3000/jucator
Content-Type: application/json

{
    "nume":"Simionescu",
    "prenume":"Andrei-Gavril",
    "pozitie":"atacant",
    "salariu": 1000
}
###
PUT http://localhost:3000/clasament:4
Content-Type: application/json

{  "echipa": "Steaua Bucuresti2",
    "meciuri": 3,
    "victorii":3,
    "infrangeri":7,
    "seturi":"8-2",
    "puncte":1
}
###
GET http://localhost:3000/clasament:?Dinamo
Content-Type: application/json
###
POST http://localhost:3000/sponsor
Content-Type: application/json

{
    "nume":"ElMagnifico"
}
###
GET http://localhost:3000/administrator

###
GET http://localhost:3000/meci

###
DELETE  http://localhost:3000/meci/1
Content-Type: application/json

{
    "echipa_unu":"Mancester United",
    "echipa_doi":"Liverpool",
    "stare":"castigat",
    "data":"2022-01-12"

}
