GET http://localhost:3000/

###
POST http://localhost:3000/
Content-Type: application/json

{
    "echipa": "FortaCLUJ",
    "meciuri": 5,
    "victorii":6,
    "infrangeri":7,
    "seturi":"8",
    "puncte":9
}
###
DELETE http://localhost:3000/delete/28

###
PUT http://localhost:3000/update-clasament/1
Content-Type: application/json

{  "echipa": "Steaua Bucuresti",
    "meciuri": 3,
    "victorii":3,
    "infrangeri":7,
    "seturi":"8-2",
    "puncte":1
}
