GET http://localhost:3000/

###
POST http://localhost:3000/add
Content-Type: application/json

{
    "echipa": "FortaCLUJ",
    "meciuri": 5,
    "victorii":6,
    "infrangeri":7,
    "seturi":"8",
    "puncte":9,
}
###
DELETE http://localhost:3000/delete/28